version: '3'

services:
  rabbitmq-broker:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: testing
      RABBITMQ_DEFAULT_PASS: secrettesting

